name: mock_generator
description: faker base mock generator
version: 1.0.7
homepage: https://github.com/snghrym

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  faker: ^1.2.1
  analyzer: ^0.39.4

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.0.0
  test: ^1.0.0
  pedantic_mono: any
