name: mock_generator
description: faker base mock generator
version: 1.0.0
author: Shingo Hirasawa <hirayamaru@gmail.com>
homepage: https://github.com/snghrym

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0