name: mock_generator
description: faker base mock generator
version: 1.3.0
homepage: https://github.com/snghrym

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  faker: ^1.2.1
  analyzer: ^0.41.0
  mock_annotation: ^1.2.0
  dart_style: ^1.3.3

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.0.0
  test: ^1.13.0
  pedantic_mono: any
  source_gen_test: any
    
# dependency_overrides:
#   mock_annotation:
#     path: ../mock_annotation
    