name: mock_usage_example
description: faker base mock generator
version: 1.1.1
homepage: https://github.com/snghrym

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  mock_annotation: ^1.2.0

dev_dependencies:
  build_test: ^1.0.0
  test: any
  pedantic_mono: any
  build_runner: ^1.0.0
  json_serializable: ^3.2.5
  mock_generator: ^1.2.0
 
dependency_overrides:
  mock_generator:
    path: ../mock_generator
  mock_annotation:
    path: ../mock_annotation
    