name: mock_example_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  mock_annotation: ^1.2.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.5
  mock_generator: ^1.2.0

dependency_overrides:
  mock_generator:
    path: ../mock_generator
  mock_annotation:
    path: ../mock_annotation

flutter:
  uses-material-design: true

